# bwa-mem-sw core files
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/batch_manager.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/bwa_mem_sw.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/FIFO_sw_pe_array_blockMatchs_V.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/FIFO_sw_pe_array_matchs_0_V.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/FIFO_sw_pe_array_seeds_0_V.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/FIFO_sw_pe_array_seeds_ctrl_0_V_V.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/nlb_gram_sdp.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/nlb_gram_ssp.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/rbb.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_fill_resulBuf.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_load_task.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_mux_25to1_sel5_8_1.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_proc_element_query_mem_V.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_proc_element.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_receive_match_matchBuf.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_receive_match.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_sw_extend_eh_arr.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_sw_extend.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array_task_parse.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/sw_pe_array.v
set_global_assignment -name VERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/tbb.v
set_global_assignment -name SYSTEMVERILOG_FILE /curr/haoyc/afu-quickassist/bwa-mem-sw/cci_std_afu.sv
