$WORKDIR/rtl/nlb/arbiter.v
$WORKDIR/rtl/nlb/nlb_lpbk.v
$WORKDIR/rtl/nlb/nlb_top.sv
$WORKDIR/rtl/nlb/requestor.v
$WORKDIR/rtl/nlb/sim_files.f
$WORKDIR/rtl/nlb/test_lpbk1.v
$WORKDIR/rtl/nlb/test_lpbk2.v
$WORKDIR/rtl/nlb/test_lpbk3.v
$WORKDIR/rtl/nlb/test_rdwr.v
$WORKDIR/rtl/nlb/test_sw1.v
$WORKDIR/rtl/nlb/nlb_gram_sdp.v
$WORKDIR/rtl/nlb/nlb_gfifo.v
$WORKDIR/rtl/nlb/nlb_sb_gfifo.v
