// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sw_pe_array_task_parse (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        partInp_address0,
        partInp_ce0,
        partInp_q0,
        seeds_0_V_din,
        seeds_0_V_full_n,
        seeds_0_V_write,
        seeds_1_V_din,
        seeds_1_V_full_n,
        seeds_1_V_write,
        seeds_2_V_din,
        seeds_2_V_full_n,
        seeds_2_V_write,
        seeds_3_V_din,
        seeds_3_V_full_n,
        seeds_3_V_write,
        seeds_4_V_din,
        seeds_4_V_full_n,
        seeds_4_V_write,
        seeds_5_V_din,
        seeds_5_V_full_n,
        seeds_5_V_write,
        seeds_6_V_din,
        seeds_6_V_full_n,
        seeds_6_V_write,
        seeds_7_V_din,
        seeds_7_V_full_n,
        seeds_7_V_write,
        seeds_8_V_din,
        seeds_8_V_full_n,
        seeds_8_V_write,
        seeds_9_V_din,
        seeds_9_V_full_n,
        seeds_9_V_write,
        seeds_ctrl_0_V_V_din,
        seeds_ctrl_0_V_V_full_n,
        seeds_ctrl_0_V_V_write,
        seeds_ctrl_1_V_V_din,
        seeds_ctrl_1_V_V_full_n,
        seeds_ctrl_1_V_V_write,
        seeds_ctrl_2_V_V_din,
        seeds_ctrl_2_V_V_full_n,
        seeds_ctrl_2_V_V_write,
        seeds_ctrl_3_V_V_din,
        seeds_ctrl_3_V_V_full_n,
        seeds_ctrl_3_V_V_write,
        seeds_ctrl_4_V_V_din,
        seeds_ctrl_4_V_V_full_n,
        seeds_ctrl_4_V_V_write,
        seeds_ctrl_5_V_V_din,
        seeds_ctrl_5_V_V_full_n,
        seeds_ctrl_5_V_V_write,
        seeds_ctrl_6_V_V_din,
        seeds_ctrl_6_V_V_full_n,
        seeds_ctrl_6_V_V_write,
        seeds_ctrl_7_V_V_din,
        seeds_ctrl_7_V_V_full_n,
        seeds_ctrl_7_V_V_write,
        seeds_ctrl_8_V_V_din,
        seeds_ctrl_8_V_V_full_n,
        seeds_ctrl_8_V_V_write,
        seeds_ctrl_9_V_V_din,
        seeds_ctrl_9_V_V_full_n,
        seeds_ctrl_9_V_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 12'b1;
parameter    ap_ST_st2_fsm_1 = 12'b10;
parameter    ap_ST_st3_fsm_2 = 12'b100;
parameter    ap_ST_st4_fsm_3 = 12'b1000;
parameter    ap_ST_st5_fsm_4 = 12'b10000;
parameter    ap_ST_st6_fsm_5 = 12'b100000;
parameter    ap_ST_st7_fsm_6 = 12'b1000000;
parameter    ap_ST_st8_fsm_7 = 12'b10000000;
parameter    ap_ST_st9_fsm_8 = 12'b100000000;
parameter    ap_ST_st10_fsm_9 = 12'b1000000000;
parameter    ap_ST_st11_fsm_10 = 12'b10000000000;
parameter    ap_ST_st12_fsm_11 = 12'b100000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv4_6 = 4'b110;
parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv64_2 = 64'b10;
parameter    ap_const_lv64_A = 64'b1010;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv31_1 = 31'b1;
parameter    ap_const_lv8_9 = 8'b1001;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [11:0] partInp_address0;
output   partInp_ce0;
input  [31:0] partInp_q0;
output  [31:0] seeds_0_V_din;
input   seeds_0_V_full_n;
output   seeds_0_V_write;
output  [31:0] seeds_1_V_din;
input   seeds_1_V_full_n;
output   seeds_1_V_write;
output  [31:0] seeds_2_V_din;
input   seeds_2_V_full_n;
output   seeds_2_V_write;
output  [31:0] seeds_3_V_din;
input   seeds_3_V_full_n;
output   seeds_3_V_write;
output  [31:0] seeds_4_V_din;
input   seeds_4_V_full_n;
output   seeds_4_V_write;
output  [31:0] seeds_5_V_din;
input   seeds_5_V_full_n;
output   seeds_5_V_write;
output  [31:0] seeds_6_V_din;
input   seeds_6_V_full_n;
output   seeds_6_V_write;
output  [31:0] seeds_7_V_din;
input   seeds_7_V_full_n;
output   seeds_7_V_write;
output  [31:0] seeds_8_V_din;
input   seeds_8_V_full_n;
output   seeds_8_V_write;
output  [31:0] seeds_9_V_din;
input   seeds_9_V_full_n;
output   seeds_9_V_write;
output  [1:0] seeds_ctrl_0_V_V_din;
input   seeds_ctrl_0_V_V_full_n;
output   seeds_ctrl_0_V_V_write;
output  [1:0] seeds_ctrl_1_V_V_din;
input   seeds_ctrl_1_V_V_full_n;
output   seeds_ctrl_1_V_V_write;
output  [1:0] seeds_ctrl_2_V_V_din;
input   seeds_ctrl_2_V_V_full_n;
output   seeds_ctrl_2_V_V_write;
output  [1:0] seeds_ctrl_3_V_V_din;
input   seeds_ctrl_3_V_V_full_n;
output   seeds_ctrl_3_V_V_write;
output  [1:0] seeds_ctrl_4_V_V_din;
input   seeds_ctrl_4_V_V_full_n;
output   seeds_ctrl_4_V_V_write;
output  [1:0] seeds_ctrl_5_V_V_din;
input   seeds_ctrl_5_V_V_full_n;
output   seeds_ctrl_5_V_V_write;
output  [1:0] seeds_ctrl_6_V_V_din;
input   seeds_ctrl_6_V_V_full_n;
output   seeds_ctrl_6_V_V_write;
output  [1:0] seeds_ctrl_7_V_V_din;
input   seeds_ctrl_7_V_V_full_n;
output   seeds_ctrl_7_V_V_write;
output  [1:0] seeds_ctrl_8_V_V_din;
input   seeds_ctrl_8_V_V_full_n;
output   seeds_ctrl_8_V_V_write;
output  [1:0] seeds_ctrl_9_V_V_din;
input   seeds_ctrl_9_V_V_full_n;
output   seeds_ctrl_9_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] partInp_address0;
reg partInp_ce0;
reg seeds_0_V_write;
reg seeds_1_V_write;
reg seeds_2_V_write;
reg seeds_3_V_write;
reg seeds_4_V_write;
reg seeds_5_V_write;
reg seeds_6_V_write;
reg seeds_7_V_write;
reg seeds_8_V_write;
reg seeds_9_V_write;
reg[1:0] seeds_ctrl_0_V_V_din;
reg seeds_ctrl_0_V_V_write;
reg[1:0] seeds_ctrl_1_V_V_din;
reg seeds_ctrl_1_V_V_write;
reg[1:0] seeds_ctrl_2_V_V_din;
reg seeds_ctrl_2_V_V_write;
reg[1:0] seeds_ctrl_3_V_V_din;
reg seeds_ctrl_3_V_V_write;
reg[1:0] seeds_ctrl_4_V_V_din;
reg seeds_ctrl_4_V_V_write;
reg[1:0] seeds_ctrl_5_V_V_din;
reg seeds_ctrl_5_V_V_write;
reg[1:0] seeds_ctrl_6_V_V_din;
reg seeds_ctrl_6_V_V_write;
reg[1:0] seeds_ctrl_7_V_V_din;
reg seeds_ctrl_7_V_V_write;
reg[1:0] seeds_ctrl_8_V_V_din;
reg seeds_ctrl_8_V_V_write;
reg[1:0] seeds_ctrl_9_V_V_din;
reg seeds_ctrl_9_V_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm = 12'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_31;
reg    ap_sig_bdd_128;
reg   [31:0] partTaskNums_reg_677;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_137;
wire   [7:0] oneTaskBuf_addr_gep_fu_466_p3;
reg   [7:0] oneTaskBuf_addr_reg_688;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_148;
reg   [31:0] staOffset_reg_693;
wire   [30:0] i_2_fu_589_p2;
reg   [30:0] i_2_reg_701;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_158;
wire   [3:0] tmp_64_fu_598_p1;
reg   [3:0] tmp_64_reg_706;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_167;
wire   [31:0] tmp_51_fu_627_p2;
reg   [31:0] tmp_51_reg_710;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_176;
wire   [15:0] i_1_fu_642_p2;
reg   [15:0] i_1_reg_718;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_185;
wire   [0:0] tmp_54_fu_637_p2;
reg    ap_sig_bdd_264;
wire   [3:0] m_1_fu_659_p2;
reg   [3:0] m_1_reg_731;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_278;
wire   [0:0] exitcond_fu_653_p2;
reg    ap_sig_bdd_338;
reg   [7:0] oneTaskBuf_address0;
reg    oneTaskBuf_ce0;
reg    oneTaskBuf_we0;
wire   [31:0] oneTaskBuf_d0;
wire   [31:0] oneTaskBuf_q0;
wire    grp_sw_pe_array_load_task_fu_564_ap_start;
wire    grp_sw_pe_array_load_task_fu_564_ap_done;
wire    grp_sw_pe_array_load_task_fu_564_ap_idle;
wire    grp_sw_pe_array_load_task_fu_564_ap_ready;
wire   [11:0] grp_sw_pe_array_load_task_fu_564_partInp_address0;
wire    grp_sw_pe_array_load_task_fu_564_partInp_ce0;
wire   [31:0] grp_sw_pe_array_load_task_fu_564_partInp_q0;
wire   [31:0] grp_sw_pe_array_load_task_fu_564_partTaskNums;
wire   [31:0] grp_sw_pe_array_load_task_fu_564_staOffset;
wire   [30:0] grp_sw_pe_array_load_task_fu_564_i;
wire   [7:0] grp_sw_pe_array_load_task_fu_564_oneTaskBuf_address0;
wire    grp_sw_pe_array_load_task_fu_564_oneTaskBuf_ce0;
wire    grp_sw_pe_array_load_task_fu_564_oneTaskBuf_we0;
wire   [31:0] grp_sw_pe_array_load_task_fu_564_oneTaskBuf_d0;
reg   [30:0] i_reg_494;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_374;
reg   [0:0] tmp_12_phi_fu_509_p20;
reg   [15:0] i_0_i_reg_541;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_432;
reg    ap_sig_bdd_463;
reg   [3:0] m_reg_552;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_472;
wire   [0:0] tmp_fu_584_p2;
reg    grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_486;
wire  signed [63:0] tmp_55_fu_648_p1;
reg   [7:0] j_fu_196;
wire   [7:0] j_2_fu_614_p3;
wire   [31:0] i_cast_fu_580_p1;
wire   [0:0] tmp_52_fu_602_p2;
wire   [7:0] j_3_fu_608_p2;
wire  signed [31:0] tmp_53_fu_633_p1;
reg   [11:0] ap_NS_fsm;
reg    ap_sig_bdd_423;


sw_pe_array_task_parse_oneTaskBuf #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
oneTaskBuf_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( oneTaskBuf_address0 ),
    .ce0( oneTaskBuf_ce0 ),
    .we0( oneTaskBuf_we0 ),
    .d0( oneTaskBuf_d0 ),
    .q0( oneTaskBuf_q0 )
);

sw_pe_array_load_task grp_sw_pe_array_load_task_fu_564(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_sw_pe_array_load_task_fu_564_ap_start ),
    .ap_done( grp_sw_pe_array_load_task_fu_564_ap_done ),
    .ap_idle( grp_sw_pe_array_load_task_fu_564_ap_idle ),
    .ap_ready( grp_sw_pe_array_load_task_fu_564_ap_ready ),
    .partInp_address0( grp_sw_pe_array_load_task_fu_564_partInp_address0 ),
    .partInp_ce0( grp_sw_pe_array_load_task_fu_564_partInp_ce0 ),
    .partInp_q0( grp_sw_pe_array_load_task_fu_564_partInp_q0 ),
    .partTaskNums( grp_sw_pe_array_load_task_fu_564_partTaskNums ),
    .staOffset( grp_sw_pe_array_load_task_fu_564_staOffset ),
    .i( grp_sw_pe_array_load_task_fu_564_i ),
    .oneTaskBuf_address0( grp_sw_pe_array_load_task_fu_564_oneTaskBuf_address0 ),
    .oneTaskBuf_ce0( grp_sw_pe_array_load_task_fu_564_oneTaskBuf_ce0 ),
    .oneTaskBuf_we0( grp_sw_pe_array_load_task_fu_564_oneTaskBuf_we0 ),
    .oneTaskBuf_d0( grp_sw_pe_array_load_task_fu_564_oneTaskBuf_d0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_bdd_338 & ~(ap_const_lv1_0 == exitcond_fu_653_p2))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_fu_584_p2))) begin
            grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sw_pe_array_load_task_fu_564_ap_ready)) begin
            grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        i_0_i_reg_541 <= i_1_reg_718;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        i_0_i_reg_541 <= ap_const_lv16_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        i_reg_494 <= i_2_reg_701;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_reg_494 <= ap_const_lv31_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) & (ap_const_lv1_0 == tmp_12_phi_fu_509_p20))) begin
        j_fu_196 <= j_2_fu_614_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_128)) begin
        j_fu_196 <= ap_const_lv8_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_fu_584_p2))) begin
        m_reg_552 <= ap_const_lv4_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        m_reg_552 <= m_1_reg_731;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & ~ap_sig_bdd_264)) begin
        i_1_reg_718 <= i_1_fu_642_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_2_reg_701 <= i_2_fu_589_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_bdd_338)) begin
        m_1_reg_731 <= m_1_fu_659_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        partTaskNums_reg_677 <= partInp_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        staOffset_reg_693 <= partInp_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        tmp_51_reg_710 <= tmp_51_fu_627_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        tmp_64_reg_706 <= tmp_64_fu_598_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_bdd_338 & ~(ap_const_lv1_0 == exitcond_fu_653_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & ~ap_sig_bdd_338 & ~(ap_const_lv1_0 == exitcond_fu_653_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_374)
begin
    if (ap_sig_bdd_374) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_278)
begin
    if (ap_sig_bdd_278) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_472)
begin
    if (ap_sig_bdd_472) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_31)
begin
    if (ap_sig_bdd_31) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_137)
begin
    if (ap_sig_bdd_137) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_148)
begin
    if (ap_sig_bdd_148) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_158)
begin
    if (ap_sig_bdd_158) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_486)
begin
    if (ap_sig_bdd_486) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_167)
begin
    if (ap_sig_bdd_167) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_176)
begin
    if (ap_sig_bdd_176) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_185)
begin
    if (ap_sig_bdd_185) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_432)
begin
    if (ap_sig_bdd_432) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// oneTaskBuf_address0 assign process. ///
always @ (oneTaskBuf_addr_reg_688 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or grp_sw_pe_array_load_task_fu_564_oneTaskBuf_address0 or ap_sig_cseq_ST_st5_fsm_4 or tmp_55_fu_648_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        oneTaskBuf_address0 = tmp_55_fu_648_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        oneTaskBuf_address0 = oneTaskBuf_addr_reg_688;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        oneTaskBuf_address0 = grp_sw_pe_array_load_task_fu_564_oneTaskBuf_address0;
    end else begin
        oneTaskBuf_address0 = 'bx;
    end
end

/// oneTaskBuf_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_bdd_264 or grp_sw_pe_array_load_task_fu_564_oneTaskBuf_ce0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & ~ap_sig_bdd_264))) begin
        oneTaskBuf_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        oneTaskBuf_ce0 = grp_sw_pe_array_load_task_fu_564_oneTaskBuf_ce0;
    end else begin
        oneTaskBuf_ce0 = ap_const_logic_0;
    end
end

/// oneTaskBuf_we0 assign process. ///
always @ (grp_sw_pe_array_load_task_fu_564_oneTaskBuf_we0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        oneTaskBuf_we0 = grp_sw_pe_array_load_task_fu_564_oneTaskBuf_we0;
    end else begin
        oneTaskBuf_we0 = ap_const_logic_0;
    end
end

/// partInp_address0 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or grp_sw_pe_array_load_task_fu_564_partInp_address0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        partInp_address0 = ap_const_lv64_A;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        partInp_address0 = ap_const_lv64_2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        partInp_address0 = grp_sw_pe_array_load_task_fu_564_partInp_address0;
    end else begin
        partInp_address0 = 'bx;
    end
end

/// partInp_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st1_fsm_0 or ap_sig_bdd_128 or ap_sig_cseq_ST_st2_fsm_1 or grp_sw_pe_array_load_task_fu_564_partInp_ce0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_128) | (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1))) begin
        partInp_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        partInp_ce0 = grp_sw_pe_array_load_task_fu_564_partInp_ce0;
    end else begin
        partInp_ce0 = ap_const_logic_0;
    end
end

/// seeds_0_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_0_V_write = ap_const_logic_1;
    end else begin
        seeds_0_V_write = ap_const_logic_0;
    end
end

/// seeds_1_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_1) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_1_V_write = ap_const_logic_1;
    end else begin
        seeds_1_V_write = ap_const_logic_0;
    end
end

/// seeds_2_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_2) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_2_V_write = ap_const_logic_1;
    end else begin
        seeds_2_V_write = ap_const_logic_0;
    end
end

/// seeds_3_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_3) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_3_V_write = ap_const_logic_1;
    end else begin
        seeds_3_V_write = ap_const_logic_0;
    end
end

/// seeds_4_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_4) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_4_V_write = ap_const_logic_1;
    end else begin
        seeds_4_V_write = ap_const_logic_0;
    end
end

/// seeds_5_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_5) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_5_V_write = ap_const_logic_1;
    end else begin
        seeds_5_V_write = ap_const_logic_0;
    end
end

/// seeds_6_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_6_V_write = ap_const_logic_1;
    end else begin
        seeds_6_V_write = ap_const_logic_0;
    end
end

/// seeds_7_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_7) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_7_V_write = ap_const_logic_1;
    end else begin
        seeds_7_V_write = ap_const_logic_0;
    end
end

/// seeds_8_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if (((tmp_64_reg_706 == ap_const_lv4_8) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_8_V_write = ap_const_logic_1;
    end else begin
        seeds_8_V_write = ap_const_logic_0;
    end
end

/// seeds_9_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_bdd_463)
begin
    if ((~(tmp_64_reg_706 == ap_const_lv4_8) & ~(tmp_64_reg_706 == ap_const_lv4_7) & ~(tmp_64_reg_706 == ap_const_lv4_6) & ~(tmp_64_reg_706 == ap_const_lv4_5) & ~(tmp_64_reg_706 == ap_const_lv4_4) & ~(tmp_64_reg_706 == ap_const_lv4_3) & ~(tmp_64_reg_706 == ap_const_lv4_2) & ~(tmp_64_reg_706 == ap_const_lv4_1) & ~(tmp_64_reg_706 == ap_const_lv4_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~ap_sig_bdd_463)) begin
        seeds_9_V_write = ap_const_logic_1;
    end else begin
        seeds_9_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_0_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_0 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_0_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_0) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_0_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_0_V_V_din = 'bx;
    end
end

/// seeds_ctrl_0_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_0) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_0 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_0_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_0_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_1_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_1 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_1_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_1) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_1_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_1_V_V_din = 'bx;
    end
end

/// seeds_ctrl_1_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_1) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_1 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_1_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_1_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_2_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_2 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_2_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_2) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_2_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_2_V_V_din = 'bx;
    end
end

/// seeds_ctrl_2_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_2) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_2 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_2_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_2_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_3_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_3 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_3_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_3) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_3_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_3_V_V_din = 'bx;
    end
end

/// seeds_ctrl_3_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_3) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_3 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_3_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_3_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_4_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_4 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_4_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_4) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_4_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_4_V_V_din = 'bx;
    end
end

/// seeds_ctrl_4_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_4) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_4 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_4_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_4_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_5_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_5 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_5_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_5) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_5_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_5_V_V_din = 'bx;
    end
end

/// seeds_ctrl_5_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_5) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_5 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_5_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_5_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_6_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_6 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_6_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_6) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_6_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_6_V_V_din = 'bx;
    end
end

/// seeds_ctrl_6_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_6) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_6 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_6_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_6_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_7_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_7 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_7_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_7) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_7_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_7_V_V_din = 'bx;
    end
end

/// seeds_ctrl_7_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & (tmp_64_reg_706 == ap_const_lv4_7) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_7 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_7_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_7_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_8_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_8 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_8_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_64_reg_706 == ap_const_lv4_8) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_8_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_8_V_V_din = 'bx;
    end
end

/// seeds_ctrl_8_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_64_reg_706 == ap_const_lv4_8) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_8 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_8_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_8_V_V_write = ap_const_logic_0;
    end
end

/// seeds_ctrl_9_V_V_din assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & ~(ap_const_lv4_8 == m_reg_552) & ~(ap_const_lv4_7 == m_reg_552) & ~(ap_const_lv4_6 == m_reg_552) & ~(ap_const_lv4_5 == m_reg_552) & ~(ap_const_lv4_4 == m_reg_552) & ~(ap_const_lv4_3 == m_reg_552) & ~(ap_const_lv4_2 == m_reg_552) & ~(ap_const_lv4_1 == m_reg_552) & ~(ap_const_lv4_0 == m_reg_552) & ~ap_sig_bdd_338)) begin
        seeds_ctrl_9_V_V_din = ap_const_lv2_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & ~(tmp_64_reg_706 == ap_const_lv4_8) & ~(tmp_64_reg_706 == ap_const_lv4_7) & ~(tmp_64_reg_706 == ap_const_lv4_6) & ~(tmp_64_reg_706 == ap_const_lv4_5) & ~(tmp_64_reg_706 == ap_const_lv4_4) & ~(tmp_64_reg_706 == ap_const_lv4_3) & ~(tmp_64_reg_706 == ap_const_lv4_2) & ~(tmp_64_reg_706 == ap_const_lv4_1) & ~(tmp_64_reg_706 == ap_const_lv4_0) & ~ap_sig_bdd_264)) begin
        seeds_ctrl_9_V_V_din = ap_const_lv2_1;
    end else begin
        seeds_ctrl_9_V_V_din = 'bx;
    end
end

/// seeds_ctrl_9_V_V_write assign process. ///
always @ (tmp_64_reg_706 or ap_sig_cseq_ST_st8_fsm_7 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or ap_sig_cseq_ST_st11_fsm_10 or exitcond_fu_653_p2 or ap_sig_bdd_338 or m_reg_552)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) & (tmp_54_fu_637_p2 == ap_const_lv1_0) & ~(tmp_64_reg_706 == ap_const_lv4_8) & ~(tmp_64_reg_706 == ap_const_lv4_7) & ~(tmp_64_reg_706 == ap_const_lv4_6) & ~(tmp_64_reg_706 == ap_const_lv4_5) & ~(tmp_64_reg_706 == ap_const_lv4_4) & ~(tmp_64_reg_706 == ap_const_lv4_3) & ~(tmp_64_reg_706 == ap_const_lv4_2) & ~(tmp_64_reg_706 == ap_const_lv4_1) & ~(tmp_64_reg_706 == ap_const_lv4_0) & ~ap_sig_bdd_264) | ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10) & (ap_const_lv1_0 == exitcond_fu_653_p2) & ~(ap_const_lv4_8 == m_reg_552) & ~(ap_const_lv4_7 == m_reg_552) & ~(ap_const_lv4_6 == m_reg_552) & ~(ap_const_lv4_5 == m_reg_552) & ~(ap_const_lv4_4 == m_reg_552) & ~(ap_const_lv4_3 == m_reg_552) & ~(ap_const_lv4_2 == m_reg_552) & ~(ap_const_lv4_1 == m_reg_552) & ~(ap_const_lv4_0 == m_reg_552) & ~ap_sig_bdd_338))) begin
        seeds_ctrl_9_V_V_write = ap_const_logic_1;
    end else begin
        seeds_ctrl_9_V_V_write = ap_const_logic_0;
    end
end

/// tmp_12_phi_fu_509_p20 assign process. ///
always @ (seeds_ctrl_0_V_V_full_n or seeds_ctrl_1_V_V_full_n or seeds_ctrl_2_V_V_full_n or seeds_ctrl_3_V_V_full_n or seeds_ctrl_4_V_V_full_n or seeds_ctrl_5_V_V_full_n or seeds_ctrl_6_V_V_full_n or seeds_ctrl_7_V_V_full_n or seeds_ctrl_8_V_V_full_n or seeds_ctrl_9_V_V_full_n or tmp_64_fu_598_p1 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_bdd_423)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        if (ap_sig_bdd_423) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_9_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_8)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_8_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_7)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_7_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_6)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_6_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_5)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_5_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_4)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_4_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_3)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_3_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_2)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_2_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_1)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_1_V_V_full_n;
        end else if ((tmp_64_fu_598_p1 == ap_const_lv4_0)) begin
            tmp_12_phi_fu_509_p20 = seeds_ctrl_0_V_V_full_n;
        end else begin
            tmp_12_phi_fu_509_p20 = 'bx;
        end
    end else begin
        tmp_12_phi_fu_509_p20 = 'bx;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_128 or tmp_54_fu_637_p2 or ap_sig_bdd_264 or exitcond_fu_653_p2 or ap_sig_bdd_338 or grp_sw_pe_array_load_task_fu_564_ap_done or tmp_12_phi_fu_509_p20 or ap_sig_bdd_463 or tmp_fu_584_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_128) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if ((ap_const_lv1_0 == tmp_fu_584_p2)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_sw_pe_array_load_task_fu_564_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            if ((ap_const_lv1_0 == tmp_12_phi_fu_509_p20)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            if (((tmp_54_fu_637_p2 == ap_const_lv1_0) & ~ap_sig_bdd_264)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else if ((~ap_sig_bdd_264 & ~(tmp_54_fu_637_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (~ap_sig_bdd_463) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st11_fsm_10 : 
        begin
            if ((~ap_sig_bdd_338 & ~(ap_const_lv1_0 == exitcond_fu_653_p2))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if (((ap_const_lv1_0 == exitcond_fu_653_p2) & ~ap_sig_bdd_338)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_128 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_128 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_137 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_137 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_148 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_148 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_158 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_158 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_167 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_167 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_176 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_176 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_185 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_185 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_264 assign process. ///
always @ (seeds_ctrl_0_V_V_full_n or seeds_ctrl_1_V_V_full_n or seeds_ctrl_2_V_V_full_n or seeds_ctrl_3_V_V_full_n or seeds_ctrl_4_V_V_full_n or seeds_ctrl_5_V_V_full_n or seeds_ctrl_6_V_V_full_n or seeds_ctrl_7_V_V_full_n or seeds_ctrl_8_V_V_full_n or seeds_ctrl_9_V_V_full_n or tmp_64_reg_706 or tmp_54_fu_637_p2)
begin
    ap_sig_bdd_264 = (((seeds_ctrl_8_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_8) & (tmp_54_fu_637_p2 == ap_const_lv1_0)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_7_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_7)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_6_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_6)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_5_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_5)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_4_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_4)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_3_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_3)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_2_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_2)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_1_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_1)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_0_V_V_full_n == ap_const_logic_0) & (tmp_64_reg_706 == ap_const_lv4_0)) | ((tmp_54_fu_637_p2 == ap_const_lv1_0) & (seeds_ctrl_9_V_V_full_n == ap_const_logic_0) & ~(tmp_64_reg_706 == ap_const_lv4_8) & ~(tmp_64_reg_706 == ap_const_lv4_7) & ~(tmp_64_reg_706 == ap_const_lv4_6) & ~(tmp_64_reg_706 == ap_const_lv4_5) & ~(tmp_64_reg_706 == ap_const_lv4_4) & ~(tmp_64_reg_706 == ap_const_lv4_3) & ~(tmp_64_reg_706 == ap_const_lv4_2) & ~(tmp_64_reg_706 == ap_const_lv4_1) & ~(tmp_64_reg_706 == ap_const_lv4_0)));
end

/// ap_sig_bdd_278 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_278 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_31 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_31 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_338 assign process. ///
always @ (seeds_ctrl_0_V_V_full_n or seeds_ctrl_1_V_V_full_n or seeds_ctrl_2_V_V_full_n or seeds_ctrl_3_V_V_full_n or seeds_ctrl_4_V_V_full_n or seeds_ctrl_5_V_V_full_n or seeds_ctrl_6_V_V_full_n or seeds_ctrl_7_V_V_full_n or seeds_ctrl_8_V_V_full_n or seeds_ctrl_9_V_V_full_n or exitcond_fu_653_p2 or m_reg_552)
begin
    ap_sig_bdd_338 = (((seeds_ctrl_8_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_8 == m_reg_552)) | ((seeds_ctrl_7_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_7 == m_reg_552)) | ((seeds_ctrl_6_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_6 == m_reg_552)) | ((seeds_ctrl_5_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_5 == m_reg_552)) | ((seeds_ctrl_4_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_4 == m_reg_552)) | ((seeds_ctrl_3_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_3 == m_reg_552)) | ((seeds_ctrl_2_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_2 == m_reg_552)) | ((seeds_ctrl_1_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_1 == m_reg_552)) | ((seeds_ctrl_0_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & (ap_const_lv4_0 == m_reg_552)) | ((seeds_ctrl_9_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_fu_653_p2) & ~(ap_const_lv4_8 == m_reg_552) & ~(ap_const_lv4_7 == m_reg_552) & ~(ap_const_lv4_6 == m_reg_552) & ~(ap_const_lv4_5 == m_reg_552) & ~(ap_const_lv4_4 == m_reg_552) & ~(ap_const_lv4_3 == m_reg_552) & ~(ap_const_lv4_2 == m_reg_552) & ~(ap_const_lv4_1 == m_reg_552) & ~(ap_const_lv4_0 == m_reg_552)));
end

/// ap_sig_bdd_374 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_374 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_423 assign process. ///
always @ (tmp_64_fu_598_p1)
begin
    ap_sig_bdd_423 = (~(tmp_64_fu_598_p1 == ap_const_lv4_8) & ~(tmp_64_fu_598_p1 == ap_const_lv4_7) & ~(tmp_64_fu_598_p1 == ap_const_lv4_6) & ~(tmp_64_fu_598_p1 == ap_const_lv4_5) & ~(tmp_64_fu_598_p1 == ap_const_lv4_4) & ~(tmp_64_fu_598_p1 == ap_const_lv4_3) & ~(tmp_64_fu_598_p1 == ap_const_lv4_2) & ~(tmp_64_fu_598_p1 == ap_const_lv4_1) & ~(tmp_64_fu_598_p1 == ap_const_lv4_0));
end

/// ap_sig_bdd_432 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_432 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_463 assign process. ///
always @ (seeds_0_V_full_n or seeds_1_V_full_n or seeds_2_V_full_n or seeds_3_V_full_n or seeds_4_V_full_n or seeds_5_V_full_n or seeds_6_V_full_n or seeds_7_V_full_n or seeds_8_V_full_n or seeds_9_V_full_n or tmp_64_reg_706)
begin
    ap_sig_bdd_463 = (((tmp_64_reg_706 == ap_const_lv4_8) & (seeds_8_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_7) & (seeds_7_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_6) & (seeds_6_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_5) & (seeds_5_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_4) & (seeds_4_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_3) & (seeds_3_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_2) & (seeds_2_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_1) & (seeds_1_V_full_n == ap_const_logic_0)) | ((tmp_64_reg_706 == ap_const_lv4_0) & (seeds_0_V_full_n == ap_const_logic_0)) | (~(tmp_64_reg_706 == ap_const_lv4_8) & ~(tmp_64_reg_706 == ap_const_lv4_7) & ~(tmp_64_reg_706 == ap_const_lv4_6) & ~(tmp_64_reg_706 == ap_const_lv4_5) & ~(tmp_64_reg_706 == ap_const_lv4_4) & ~(tmp_64_reg_706 == ap_const_lv4_3) & ~(tmp_64_reg_706 == ap_const_lv4_2) & ~(tmp_64_reg_706 == ap_const_lv4_1) & ~(tmp_64_reg_706 == ap_const_lv4_0) & (seeds_9_V_full_n == ap_const_logic_0)));
end

/// ap_sig_bdd_472 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_472 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_486 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_486 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end
assign exitcond_fu_653_p2 = (m_reg_552 == ap_const_lv4_A? 1'b1: 1'b0);
assign grp_sw_pe_array_load_task_fu_564_ap_start = grp_sw_pe_array_load_task_fu_564_ap_start_ap_start_reg;
assign grp_sw_pe_array_load_task_fu_564_i = i_reg_494;
assign grp_sw_pe_array_load_task_fu_564_partInp_q0 = partInp_q0;
assign grp_sw_pe_array_load_task_fu_564_partTaskNums = partTaskNums_reg_677;
assign grp_sw_pe_array_load_task_fu_564_staOffset = staOffset_reg_693;
assign i_1_fu_642_p2 = (i_0_i_reg_541 + ap_const_lv16_1);
assign i_2_fu_589_p2 = (i_reg_494 + ap_const_lv31_1);
assign i_cast_fu_580_p1 = i_reg_494;
assign j_2_fu_614_p3 = ((tmp_52_fu_602_p2)? ap_const_lv8_0: j_3_fu_608_p2);
assign j_3_fu_608_p2 = (j_fu_196 + ap_const_lv8_1);
assign m_1_fu_659_p2 = (m_reg_552 + ap_const_lv4_1);
assign oneTaskBuf_addr_gep_fu_466_p3 = ap_const_lv64_0;
assign oneTaskBuf_d0 = grp_sw_pe_array_load_task_fu_564_oneTaskBuf_d0;
assign seeds_0_V_din = oneTaskBuf_q0;
assign seeds_1_V_din = oneTaskBuf_q0;
assign seeds_2_V_din = oneTaskBuf_q0;
assign seeds_3_V_din = oneTaskBuf_q0;
assign seeds_4_V_din = oneTaskBuf_q0;
assign seeds_5_V_din = oneTaskBuf_q0;
assign seeds_6_V_din = oneTaskBuf_q0;
assign seeds_7_V_din = oneTaskBuf_q0;
assign seeds_8_V_din = oneTaskBuf_q0;
assign seeds_9_V_din = oneTaskBuf_q0;
assign tmp_51_fu_627_p2 = (oneTaskBuf_q0 + ap_const_lv32_1);
assign tmp_52_fu_602_p2 = ($signed(j_fu_196) > $signed(8'b1001)? 1'b1: 1'b0);
assign tmp_53_fu_633_p1 = $signed(i_0_i_reg_541);
assign tmp_54_fu_637_p2 = ($signed(tmp_53_fu_633_p1) < $signed(tmp_51_reg_710)? 1'b1: 1'b0);
assign tmp_55_fu_648_p1 = $signed(i_0_i_reg_541);
assign tmp_64_fu_598_p1 = j_fu_196[3:0];
assign tmp_fu_584_p2 = ($signed(i_cast_fu_580_p1) < $signed(partTaskNums_reg_677)? 1'b1: 1'b0);
always @ (posedge ap_clk)
begin
    oneTaskBuf_addr_reg_688[7:0] <= 8'b00000000;
end



endmodule //sw_pe_array_task_parse

