// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sw_pe_array_proc_element (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        pe_seeds_V_dout,
        pe_seeds_V_empty_n,
        pe_seeds_V_read,
        pe_seeds_ctrl_V_V_dout,
        pe_seeds_ctrl_V_V_empty_n,
        pe_seeds_ctrl_V_V_read,
        pe_matchs_V_din,
        pe_matchs_V_full_n,
        pe_matchs_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 21'b1;
parameter    ap_ST_st2_fsm_1 = 21'b10;
parameter    ap_ST_st3_fsm_2 = 21'b100;
parameter    ap_ST_st4_fsm_3 = 21'b1000;
parameter    ap_ST_st5_fsm_4 = 21'b10000;
parameter    ap_ST_st6_fsm_5 = 21'b100000;
parameter    ap_ST_st7_fsm_6 = 21'b1000000;
parameter    ap_ST_st8_fsm_7 = 21'b10000000;
parameter    ap_ST_st9_fsm_8 = 21'b100000000;
parameter    ap_ST_st10_fsm_9 = 21'b1000000000;
parameter    ap_ST_st11_fsm_10 = 21'b10000000000;
parameter    ap_ST_st12_fsm_11 = 21'b100000000000;
parameter    ap_ST_st13_fsm_12 = 21'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 21'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 21'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 21'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 21'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 21'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 21'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 21'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 21'b100000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv16_FFFF = 16'b1111111111111111;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1A = 32'b11010;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] pe_seeds_V_dout;
input   pe_seeds_V_empty_n;
output   pe_seeds_V_read;
input  [1:0] pe_seeds_ctrl_V_V_dout;
input   pe_seeds_ctrl_V_V_empty_n;
output   pe_seeds_ctrl_V_V_read;
output  [31:0] pe_matchs_V_din;
input   pe_matchs_V_full_n;
output   pe_matchs_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pe_seeds_V_read;
reg pe_seeds_ctrl_V_V_read;
reg[31:0] pe_matchs_V_din;
reg pe_matchs_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm = 21'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_40;
wire   [7:0] o_del_fu_732_p1;
reg   [7:0] o_del_reg_1168;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_66;
wire   [0:0] tmp_nbreadreq_fu_132_p3;
wire   [0:0] tmp_s_fu_726_p2;
reg    ap_sig_bdd_85;
reg   [7:0] e_del_reg_1173;
reg   [7:0] o_ins_reg_1178;
reg   [7:0] e_ins_reg_1183;
reg   [31:0] tmp_105_reg_1188;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_102;
reg   [7:0] w_in_reg_1194;
wire   [7:0] qlen_0_fu_756_p1;
reg   [7:0] qlen_0_reg_1200;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_114;
reg   [10:0] tlen_0_V_reg_1206;
wire   [7:0] qlen_1_fu_760_p1;
reg   [7:0] qlen_1_reg_1212;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_126;
reg   [10:0] tlen_1_V_reg_1219;
wire   [15:0] regScore_fu_764_p1;
reg   [15:0] regScore_reg_1225;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_137;
reg   [15:0] qBeg_ori_reg_1231;
wire   [7:0] h0_fu_778_p1;
reg   [7:0] h0_reg_1236;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_149;
reg   [31:0] tmp_110_reg_1241;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_158;
reg   [31:0] tmp_111_reg_1246;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_167;
reg   [31:0] tmp_98_reg_1251;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_176;
wire  signed [15:0] aw_0_fu_782_p1;
reg  signed [15:0] aw_0_reg_1256;
wire   [15:0] qEnd_fu_785_p1;
reg   [15:0] qEnd_reg_1262;
wire   [10:0] ts_baddr_V_2_cast_fu_800_p1;
reg   [10:0] ts_baddr_V_2_cast_reg_1268;
wire   [8:0] p_0338_0_i_fu_844_p3;
reg   [8:0] p_0338_0_i_reg_1273;
wire   [8:0] k_V_fu_857_p2;
reg   [8:0] k_V_reg_1281;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_194;
wire   [0:0] exitcond565_i_fu_852_p2;
reg    ap_sig_bdd_199;
wire   [10:0] r_V_fu_867_p3;
reg   [10:0] r_V_reg_1291;
wire   [3:0] l_V_fu_881_p2;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_213;
wire   [31:0] tmp_qr_data_1_fu_912_p2;
wire   [0:0] exitcond564_i_fu_875_p2;
wire   [1:0] i_V_fu_924_p2;
reg   [1:0] i_V_reg_1312;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_227;
wire   [0:0] exitcond_i_fu_918_p2;
reg    ap_sig_bdd_233;
wire   [0:0] tmp_99_fu_930_p1;
reg   [0:0] tmp_99_reg_1317;
wire   [7:0] op2_assign_fu_935_p3;
reg   [7:0] op2_assign_reg_1325;
wire   [0:0] tmp_62_fu_942_p2;
reg   [0:0] tmp_62_reg_1331;
wire   [10:0] grp_fu_708_p3;
reg   [10:0] p_08_phi_reg_1335;
wire   [7:0] tmp_63_fu_952_p3;
reg   [7:0] tmp_63_reg_1340;
wire   [15:0] tmp_101_fu_966_p1;
reg   [15:0] tmp_101_reg_1345;
reg   [15:0] max_del_load_phi_reg_1350;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_261;
wire    grp_sw_pe_array_sw_extend_fu_657_ap_done;
wire   [15:0] width_3_fu_990_p3;
wire   [15:0] aw_1_2_fu_997_p3;
wire   [15:0] trueScore_2_fu_1073_p2;
wire   [0:0] tmp_64_fu_1024_p2;
wire   [0:0] tmp_68_fu_1067_p2;
wire   [0:0] grp_fu_714_p2;
wire   [15:0] rBeg_fu_1079_p2;
wire   [15:0] trueScore_4_fu_1085_p2;
wire   [15:0] qBeg_fu_1091_p2;
wire   [15:0] rBeg_1_fu_1096_p2;
wire   [8:0] qs_baddr_V_fu_1105_p2;
reg   [8:0] qs_baddr_V_reg_1465;
wire   [10:0] ts_baddr_V_fu_1111_p2;
reg   [10:0] ts_baddr_V_reg_1470;
wire   [15:0] width_2_fu_1132_p3;
reg   [15:0] width_2_reg_1475;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_330;
reg   [10:0] query_mem_V_address0;
reg    query_mem_V_ce0;
reg    query_mem_V_we0;
wire   [3:0] query_mem_V_d0;
wire   [3:0] query_mem_V_q0;
wire    grp_sw_pe_array_sw_extend_fu_657_ap_start;
wire    grp_sw_pe_array_sw_extend_fu_657_ap_idle;
wire    grp_sw_pe_array_sw_extend_fu_657_ap_ready;
wire   [8:0] grp_sw_pe_array_sw_extend_fu_657_qs_baddr_V;
wire   [10:0] grp_sw_pe_array_sw_extend_fu_657_qs_V_address0;
wire    grp_sw_pe_array_sw_extend_fu_657_qs_V_ce0;
wire   [3:0] grp_sw_pe_array_sw_extend_fu_657_qs_V_q0;
wire   [10:0] grp_sw_pe_array_sw_extend_fu_657_ts_baddr_V;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_qlen;
wire   [10:0] grp_sw_pe_array_sw_extend_fu_657_tlen_V;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_o_ins;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_e_ins;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_o_del;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_e_del;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_w_in;
wire   [7:0] grp_sw_pe_array_sw_extend_fu_657_h0;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_regScore_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_max_ins;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_max_del;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_qle_ret_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_tle_ret_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_gtle_ret_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_gscore_ret_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_maxoff_ret_read;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_0;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_1;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_2;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_3;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_4;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_5;
wire   [15:0] grp_sw_pe_array_sw_extend_fu_657_ap_return_6;
reg   [8:0] p_0209_0_i_reg_171;
reg   [3:0] p_0196_0_i_reg_182;
reg   [31:0] p_0201_0_i_reg_193;
reg   [15:0] width_reg_202;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_394;
reg   [15:0] width_1_reg_212;
reg   [15:0] maxoff_reg_222;
reg   [15:0] gscore_reg_234;
reg   [15:0] gtle_reg_246;
reg   [15:0] tle_reg_258;
reg   [15:0] qle_reg_270;
reg   [15:0] sc0_reg_282;
reg   [1:0] p_0121_0_i_reg_292;
reg   [8:0] p_0_reg_304;
reg   [10:0] p_s_reg_316;
wire   [15:0] qBeg_0_i_phi_fu_330_p4;
reg   [15:0] qBeg_0_i_reg_326;
wire   [15:0] rBeg_0_i_phi_fu_342_p4;
reg   [15:0] rBeg_0_i_reg_338;
wire   [15:0] qEnd_0_i_phi_fu_353_p4;
reg   [15:0] qEnd_0_i_reg_350;
wire   [15:0] rEnd_0_i_phi_fu_364_p4;
reg   [15:0] rEnd_0_i_reg_360;
reg   [15:0] score_0_i_reg_372;
reg   [15:0] trueScore_0_i_reg_384;
reg   [15:0] aw_0_2_reg_394;
reg   [15:0] aw_1_2_63_reg_412;
reg   [15:0] maxoff_1_reg_430;
reg   [15:0] gscore_1_reg_448;
reg   [15:0] gtle_1_reg_466;
reg   [15:0] tle_1_reg_484;
reg   [15:0] qle_1_reg_502;
reg   [15:0] regScore_1_reg_520;
reg   [15:0] qBeg_4_i_reg_538;
reg   [15:0] rBeg_4_i_reg_560;
reg   [15:0] qEnd_4_i_reg_580;
reg   [15:0] rEnd_4_i_reg_600;
reg   [15:0] score_1_i_reg_620;
reg   [15:0] trueScore_4_i_reg_638;
reg    grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_65_fu_896_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_485;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_504;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_514;
reg    ap_sig_cseq_ST_st21_fsm_20;
reg    ap_sig_bdd_523;
wire   [31:0] tmp_25_fu_1117_p3;
wire   [31:0] tmp_27_fu_1140_p3;
wire   [31:0] tmp_29_fu_1149_p3;
wire   [31:0] tmp_31_fu_1158_p1;
reg   [0:0] grp_fu_708_p0;
wire   [8:0] tmp_132_cast_fu_791_p1;
wire   [8:0] tmp_131_cast_fu_788_p1;
wire   [8:0] ts_baddr_V_2_fu_794_p2;
wire   [10:0] tmp1_fu_804_p2;
wire   [10:0] qrLen_div8_V_fu_809_p2;
wire   [2:0] tmp_95_fu_814_p1;
wire   [7:0] tmp_23_fu_824_p4;
wire   [8:0] r_V_8_cast_fu_834_p1;
wire   [0:0] tmp_58_fu_818_p2;
wire   [8:0] qrLen_div8_V_2_fu_838_p2;
wire   [7:0] tmp_97_fu_863_p1;
wire   [10:0] rhs_V_cast_fu_887_p1;
wire   [10:0] r_V_1_fu_891_p2;
wire   [7:0] tmp_100_fu_948_p1;
wire   [31:0] max_ins_load_phi_v_fu_960_p3;
wire   [7:0] tmp_35_fu_1038_p4;
wire   [7:0] tmp_103_fu_1047_p1;
wire   [7:0] tmp_37_fu_1050_p3;
wire  signed [16:0] tmp_147_cast_fu_1034_p1;
wire  signed [16:0] tmp_151_cast_fu_1057_p1;
wire   [16:0] tmp_146_cast_fu_1030_p1;
wire  signed [16:0] tmp_67_fu_1061_p2;
wire   [15:0] grp_fu_720_p2;
wire   [8:0] tmp_158_cast_fu_1102_p1;
wire   [0:0] tmp_60_fu_1126_p2;
reg   [20:0] ap_NS_fsm;
reg    ap_sig_bdd_868;


sw_pe_array_proc_element_query_mem_V #(
    .DataWidth( 4 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
query_mem_V_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( query_mem_V_address0 ),
    .ce0( query_mem_V_ce0 ),
    .we0( query_mem_V_we0 ),
    .d0( query_mem_V_d0 ),
    .q0( query_mem_V_q0 )
);

sw_pe_array_sw_extend grp_sw_pe_array_sw_extend_fu_657(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_sw_pe_array_sw_extend_fu_657_ap_start ),
    .ap_done( grp_sw_pe_array_sw_extend_fu_657_ap_done ),
    .ap_idle( grp_sw_pe_array_sw_extend_fu_657_ap_idle ),
    .ap_ready( grp_sw_pe_array_sw_extend_fu_657_ap_ready ),
    .qs_baddr_V( grp_sw_pe_array_sw_extend_fu_657_qs_baddr_V ),
    .qs_V_address0( grp_sw_pe_array_sw_extend_fu_657_qs_V_address0 ),
    .qs_V_ce0( grp_sw_pe_array_sw_extend_fu_657_qs_V_ce0 ),
    .qs_V_q0( grp_sw_pe_array_sw_extend_fu_657_qs_V_q0 ),
    .ts_baddr_V( grp_sw_pe_array_sw_extend_fu_657_ts_baddr_V ),
    .qlen( grp_sw_pe_array_sw_extend_fu_657_qlen ),
    .tlen_V( grp_sw_pe_array_sw_extend_fu_657_tlen_V ),
    .o_ins( grp_sw_pe_array_sw_extend_fu_657_o_ins ),
    .e_ins( grp_sw_pe_array_sw_extend_fu_657_e_ins ),
    .o_del( grp_sw_pe_array_sw_extend_fu_657_o_del ),
    .e_del( grp_sw_pe_array_sw_extend_fu_657_e_del ),
    .w_in( grp_sw_pe_array_sw_extend_fu_657_w_in ),
    .h0( grp_sw_pe_array_sw_extend_fu_657_h0 ),
    .regScore_read( grp_sw_pe_array_sw_extend_fu_657_regScore_read ),
    .max_ins( grp_sw_pe_array_sw_extend_fu_657_max_ins ),
    .max_del( grp_sw_pe_array_sw_extend_fu_657_max_del ),
    .qle_ret_read( grp_sw_pe_array_sw_extend_fu_657_qle_ret_read ),
    .tle_ret_read( grp_sw_pe_array_sw_extend_fu_657_tle_ret_read ),
    .gtle_ret_read( grp_sw_pe_array_sw_extend_fu_657_gtle_ret_read ),
    .gscore_ret_read( grp_sw_pe_array_sw_extend_fu_657_gscore_ret_read ),
    .maxoff_ret_read( grp_sw_pe_array_sw_extend_fu_657_maxoff_ret_read ),
    .ap_return_0( grp_sw_pe_array_sw_extend_fu_657_ap_return_0 ),
    .ap_return_1( grp_sw_pe_array_sw_extend_fu_657_ap_return_1 ),
    .ap_return_2( grp_sw_pe_array_sw_extend_fu_657_ap_return_2 ),
    .ap_return_3( grp_sw_pe_array_sw_extend_fu_657_ap_return_3 ),
    .ap_return_4( grp_sw_pe_array_sw_extend_fu_657_ap_return_4 ),
    .ap_return_5( grp_sw_pe_array_sw_extend_fu_657_ap_return_5 ),
    .ap_return_6( grp_sw_pe_array_sw_extend_fu_657_ap_return_6 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & (ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
            grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sw_pe_array_sw_extend_fu_657_ap_ready)) begin
            grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        aw_0_2_reg_394 <= width_3_fu_990_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        aw_0_2_reg_394 <= width_reg_202;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        aw_1_2_63_reg_412 <= aw_1_2_fu_997_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        aw_1_2_63_reg_412 <= width_1_reg_212;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        gscore_1_reg_448 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        gscore_1_reg_448 <= gscore_reg_234;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        gscore_reg_234 <= ap_const_lv16_FFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        gscore_reg_234 <= gscore_1_reg_448;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        gtle_1_reg_466 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        gtle_1_reg_466 <= gtle_reg_246;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        gtle_reg_246 <= ap_const_lv16_FFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        gtle_reg_246 <= gtle_1_reg_466;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        maxoff_1_reg_430 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        maxoff_1_reg_430 <= maxoff_reg_222;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        maxoff_reg_222 <= ap_const_lv16_FFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        maxoff_reg_222 <= maxoff_1_reg_430;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        p_0121_0_i_reg_292 <= ap_const_lv2_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        p_0121_0_i_reg_292 <= i_V_reg_1312;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & (ap_const_lv1_0 == exitcond564_i_fu_875_p2))) begin
        p_0196_0_i_reg_182 <= l_V_fu_881_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond565_i_fu_852_p2) & ~ap_sig_bdd_199)) begin
        p_0196_0_i_reg_182 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & (ap_const_lv1_0 == exitcond564_i_fu_875_p2))) begin
        p_0201_0_i_reg_193 <= tmp_qr_data_1_fu_912_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond565_i_fu_852_p2) & ~ap_sig_bdd_199)) begin
        p_0201_0_i_reg_193 <= pe_seeds_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ~(ap_const_lv1_0 == exitcond564_i_fu_875_p2))) begin
        p_0209_0_i_reg_171 <= k_V_reg_1281;
    end else if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11))) begin
        p_0209_0_i_reg_171 <= ap_const_lv9_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        p_0_reg_304 <= ap_const_lv9_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        p_0_reg_304 <= qs_baddr_V_reg_1465;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        p_s_reg_316 <= ts_baddr_V_2_cast_reg_1268;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        p_s_reg_316 <= ts_baddr_V_reg_1470;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        qBeg_0_i_reg_326 <= ap_const_lv16_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        qBeg_0_i_reg_326 <= qBeg_4_i_reg_538;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))) begin
        qBeg_4_i_reg_538 <= ap_const_lv16_0;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        qBeg_4_i_reg_538 <= qBeg_0_i_reg_326;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))))) begin
        qBeg_4_i_reg_538 <= qBeg_fu_1091_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        qBeg_4_i_reg_538 <= qBeg_0_i_phi_fu_330_p4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        qEnd_0_i_reg_350 <= qEnd_reg_1262;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        qEnd_0_i_reg_350 <= qEnd_4_i_reg_580;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))) begin
        qEnd_4_i_reg_580 <= qEnd_reg_1262;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))))) begin
        qEnd_4_i_reg_580 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_2;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        qEnd_4_i_reg_580 <= qEnd_0_i_reg_350;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        qEnd_4_i_reg_580 <= qEnd_0_i_phi_fu_353_p4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        qle_1_reg_502 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        qle_1_reg_502 <= qle_reg_270;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        qle_reg_270 <= ap_const_lv16_FFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        qle_reg_270 <= qle_1_reg_502;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        rBeg_0_i_reg_338 <= ap_const_lv16_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        rBeg_0_i_reg_338 <= rBeg_4_i_reg_560;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))) begin
        rBeg_4_i_reg_560 <= rBeg_fu_1079_p2;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        rBeg_4_i_reg_560 <= rBeg_0_i_reg_338;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))))) begin
        rBeg_4_i_reg_560 <= rBeg_1_fu_1096_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        rBeg_4_i_reg_560 <= rBeg_0_i_phi_fu_342_p4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        rEnd_0_i_reg_360 <= ap_const_lv16_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        rEnd_0_i_reg_360 <= rEnd_4_i_reg_600;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))) begin
        rEnd_4_i_reg_600 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))))) begin
        rEnd_4_i_reg_600 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_3;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        rEnd_4_i_reg_600 <= rEnd_0_i_reg_360;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        rEnd_4_i_reg_600 <= rEnd_0_i_phi_fu_364_p4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        regScore_1_reg_520 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        regScore_1_reg_520 <= sc0_reg_282;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        sc0_reg_282 <= regScore_reg_1225;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        sc0_reg_282 <= regScore_1_reg_520;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        score_0_i_reg_372 <= ap_const_lv16_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        score_0_i_reg_372 <= score_1_i_reg_620;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        score_1_i_reg_620 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        score_1_i_reg_620 <= score_0_i_reg_372;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2)))))) begin
        tle_1_reg_484 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        tle_1_reg_484 <= tle_reg_258;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        tle_reg_258 <= ap_const_lv16_FFFF;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        tle_reg_258 <= tle_1_reg_484;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        trueScore_0_i_reg_384 <= regScore_reg_1225;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        trueScore_0_i_reg_384 <= trueScore_4_i_reg_638;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))) begin
        trueScore_4_i_reg_638 <= trueScore_2_fu_1073_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (ap_const_lv1_0 == tmp_64_fu_1024_p2) & ~(ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))) begin
        trueScore_4_i_reg_638 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & (ap_const_lv1_0 == grp_fu_714_p2))))) begin
        trueScore_4_i_reg_638 <= trueScore_4_fu_1085_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)) & (((ap_const_lv1_0 == tmp_62_reg_1331) & ~(ap_const_lv1_0 == grp_fu_714_p2) & ~(ap_const_lv1_0 == tmp_64_fu_1024_p2)) | ((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_lv1_0 == tmp_68_fu_1067_p2) & ~(ap_const_lv1_0 == grp_fu_714_p2))))) begin
        trueScore_4_i_reg_638 <= grp_sw_pe_array_sw_extend_fu_657_ap_return_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & ~(ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        trueScore_4_i_reg_638 <= trueScore_0_i_reg_384;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        width_1_reg_212 <= aw_0_reg_1256;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        width_1_reg_212 <= aw_1_2_63_reg_412;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
        width_reg_202 <= aw_0_reg_1256;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        width_reg_202 <= aw_0_2_reg_394;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11))) begin
        aw_0_reg_1256 <= aw_0_fu_782_p1;
        p_0338_0_i_reg_1273 <= p_0338_0_i_fu_844_p3;
        qEnd_reg_1262[7 : 0] <= qEnd_fu_785_p1[7 : 0];
        tmp_98_reg_1251 <= pe_seeds_V_dout;
        ts_baddr_V_2_cast_reg_1268[8 : 0] <= ts_baddr_V_2_cast_fu_800_p1[8 : 0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
        e_del_reg_1173 <= {{pe_seeds_V_dout[ap_const_lv32_F : ap_const_lv32_8]}};
        e_ins_reg_1183 <= {{pe_seeds_V_dout[ap_const_lv32_1F : ap_const_lv32_18]}};
        o_del_reg_1168 <= o_del_fu_732_p1;
        o_ins_reg_1178 <= {{pe_seeds_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8))) begin
        h0_reg_1236 <= h0_fu_778_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_233)) begin
        i_V_reg_1312 <= i_V_fu_924_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~ap_sig_bdd_199)) begin
        k_V_reg_1281 <= k_V_fu_857_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233 & (ap_const_lv1_0 == tmp_62_fu_942_p2))) begin
        max_del_load_phi_reg_1350 <= {{max_ins_load_phi_v_fu_960_p3[ap_const_lv32_1F : ap_const_lv32_10]}};
        p_08_phi_reg_1335 <= grp_fu_708_p3;
        tmp_101_reg_1345 <= tmp_101_fu_966_p1;
        tmp_63_reg_1340 <= tmp_63_fu_952_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233)) begin
        op2_assign_reg_1325 <= op2_assign_fu_935_p3;
        tmp_62_reg_1331 <= tmp_62_fu_942_p2;
        tmp_99_reg_1317 <= tmp_99_fu_930_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7))) begin
        qBeg_ori_reg_1231 <= {{pe_seeds_V_dout[ap_const_lv32_1F : ap_const_lv32_10]}};
        regScore_reg_1225 <= regScore_fu_764_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        qlen_0_reg_1200 <= qlen_0_fu_756_p1;
        tlen_0_V_reg_1206 <= {{pe_seeds_V_dout[ap_const_lv32_1A : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5))) begin
        qlen_1_reg_1212 <= qlen_1_fu_760_p1;
        tlen_1_V_reg_1219 <= {{pe_seeds_V_dout[ap_const_lv32_1A : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done)))) begin
        qs_baddr_V_reg_1465 <= qs_baddr_V_fu_1105_p2;
        ts_baddr_V_reg_1470 <= ts_baddr_V_fu_1111_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond565_i_fu_852_p2) & ~ap_sig_bdd_199)) begin
        r_V_reg_1291[10 : 3] <= r_V_fu_867_p3[10 : 3];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(pe_seeds_V_empty_n == ap_const_logic_0))) begin
        tmp_105_reg_1188 <= pe_seeds_V_dout;
        w_in_reg_1194 <= {{pe_seeds_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9))) begin
        tmp_110_reg_1241 <= pe_seeds_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        tmp_111_reg_1246 <= pe_seeds_V_dout;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & ~(pe_matchs_V_full_n == ap_const_logic_0))) begin
        width_2_reg_1475 <= width_2_fu_1132_p3;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st10_fsm_9 assign process. ///
always @ (ap_sig_bdd_158)
begin
    if (ap_sig_bdd_158) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_167)
begin
    if (ap_sig_bdd_167) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_176)
begin
    if (ap_sig_bdd_176) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_12 assign process. ///
always @ (ap_sig_bdd_194)
begin
    if (ap_sig_bdd_194) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_13 assign process. ///
always @ (ap_sig_bdd_213)
begin
    if (ap_sig_bdd_213) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_14 assign process. ///
always @ (ap_sig_bdd_227)
begin
    if (ap_sig_bdd_227) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st16_fsm_15 assign process. ///
always @ (ap_sig_bdd_261)
begin
    if (ap_sig_bdd_261) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st17_fsm_16 assign process. ///
always @ (ap_sig_bdd_394)
begin
    if (ap_sig_bdd_394) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st18_fsm_17 assign process. ///
always @ (ap_sig_bdd_504)
begin
    if (ap_sig_bdd_504) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st19_fsm_18 assign process. ///
always @ (ap_sig_bdd_330)
begin
    if (ap_sig_bdd_330) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_40)
begin
    if (ap_sig_bdd_40) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st20_fsm_19 assign process. ///
always @ (ap_sig_bdd_514)
begin
    if (ap_sig_bdd_514) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st21_fsm_20 assign process. ///
always @ (ap_sig_bdd_523)
begin
    if (ap_sig_bdd_523) begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_66)
begin
    if (ap_sig_bdd_66) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_102)
begin
    if (ap_sig_bdd_102) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_114)
begin
    if (ap_sig_bdd_114) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_126)
begin
    if (ap_sig_bdd_126) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_485)
begin
    if (ap_sig_bdd_485) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st8_fsm_7 assign process. ///
always @ (ap_sig_bdd_137)
begin
    if (ap_sig_bdd_137) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st9_fsm_8 assign process. ///
always @ (ap_sig_bdd_149)
begin
    if (ap_sig_bdd_149) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

/// grp_fu_708_p0 assign process. ///
always @ (ap_sig_cseq_ST_st15_fsm_14 or tmp_99_fu_930_p1 or tmp_99_reg_1317 or ap_sig_cseq_ST_st16_fsm_15)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        grp_fu_708_p0 = tmp_99_reg_1317;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        grp_fu_708_p0 = tmp_99_fu_930_p1;
    end else begin
        grp_fu_708_p0 = 'bx;
    end
end

/// pe_matchs_V_din assign process. ///
always @ (pe_matchs_V_full_n or ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85 or tmp_98_reg_1251 or ap_sig_cseq_ST_st15_fsm_14 or exitcond_i_fu_918_p2 or ap_sig_bdd_233 or ap_sig_cseq_ST_st19_fsm_18 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st21_fsm_20 or tmp_25_fu_1117_p3 or tmp_27_fu_1140_p3 or tmp_29_fu_1149_p3 or tmp_31_fu_1158_p1)
begin
    if ((~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20))) begin
        pe_matchs_V_din = tmp_31_fu_1158_p1;
    end else if ((~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19))) begin
        pe_matchs_V_din = tmp_29_fu_1149_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & ~(pe_matchs_V_full_n == ap_const_logic_0))) begin
        pe_matchs_V_din = tmp_27_fu_1140_p3;
    end else if ((~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17))) begin
        pe_matchs_V_din = tmp_25_fu_1117_p3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~(ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233)) begin
        pe_matchs_V_din = tmp_98_reg_1251;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
        pe_matchs_V_din = ap_const_lv32_FFFFFFFF;
    end else begin
        pe_matchs_V_din = 'bx;
    end
end

/// pe_matchs_V_write assign process. ///
always @ (pe_matchs_V_full_n or ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85 or ap_sig_cseq_ST_st15_fsm_14 or exitcond_i_fu_918_p2 or ap_sig_bdd_233 or ap_sig_cseq_ST_st19_fsm_18 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st20_fsm_19 or ap_sig_cseq_ST_st21_fsm_20)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18) & ~(pe_matchs_V_full_n == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85) | ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~(ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233) | (~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) | (~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) | (~(pe_matchs_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20)))) begin
        pe_matchs_V_write = ap_const_logic_1;
    end else begin
        pe_matchs_V_write = ap_const_logic_0;
    end
end

/// pe_seeds_V_read assign process. ///
always @ (pe_seeds_V_empty_n or ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st5_fsm_4 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st11_fsm_10 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or exitcond565_i_fu_852_p2 or ap_sig_bdd_199 or ap_sig_cseq_ST_st7_fsm_6)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(pe_seeds_V_empty_n == ap_const_logic_0)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & (ap_const_lv1_0 == exitcond565_i_fu_852_p2) & ~ap_sig_bdd_199) | (~(pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6)))) begin
        pe_seeds_V_read = ap_const_logic_1;
    end else begin
        pe_seeds_V_read = ap_const_logic_0;
    end
end

/// pe_seeds_ctrl_V_V_read assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp_nbreadreq_fu_132_p3 or ap_sig_bdd_85)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~ap_sig_bdd_85)) begin
        pe_seeds_ctrl_V_V_read = ap_const_logic_1;
    end else begin
        pe_seeds_ctrl_V_V_read = ap_const_logic_0;
    end
end

/// query_mem_V_address0 assign process. ///
always @ (ap_sig_cseq_ST_st14_fsm_13 or tmp_62_reg_1331 or ap_sig_cseq_ST_st16_fsm_15 or grp_sw_pe_array_sw_extend_fu_657_qs_V_address0 or tmp_65_fu_896_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        query_mem_V_address0 = tmp_65_fu_896_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331))) begin
        query_mem_V_address0 = grp_sw_pe_array_sw_extend_fu_657_qs_V_address0;
    end else begin
        query_mem_V_address0 = 'bx;
    end
end

/// query_mem_V_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st14_fsm_13 or tmp_62_reg_1331 or ap_sig_cseq_ST_st16_fsm_15 or grp_sw_pe_array_sw_extend_fu_657_qs_V_ce0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        query_mem_V_ce0 = ap_const_logic_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == tmp_62_reg_1331))) begin
        query_mem_V_ce0 = grp_sw_pe_array_sw_extend_fu_657_qs_V_ce0;
    end else begin
        query_mem_V_ce0 = ap_const_logic_0;
    end
end

/// query_mem_V_we0 assign process. ///
always @ (ap_sig_cseq_ST_st14_fsm_13 or exitcond564_i_fu_875_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & (ap_const_lv1_0 == exitcond564_i_fu_875_p2))) begin
        query_mem_V_we0 = ap_const_logic_1;
    end else begin
        query_mem_V_we0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or pe_seeds_V_empty_n or pe_matchs_V_full_n or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2 or ap_sig_bdd_85 or exitcond565_i_fu_852_p2 or ap_sig_bdd_199 or exitcond564_i_fu_875_p2 or exitcond_i_fu_918_p2 or ap_sig_bdd_233 or tmp_62_reg_1331 or grp_sw_pe_array_sw_extend_fu_657_ap_done or ap_sig_bdd_868)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_868) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if ((~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_726_p2) & ~ap_sig_bdd_85)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if (((tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & ~ap_sig_bdd_85)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st8_fsm_7 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st12_fsm_11 : 
        begin
            if (~(pe_seeds_V_empty_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st12_fsm_11;
            end
        end
        ap_ST_st13_fsm_12 : 
        begin
            if (((ap_const_lv1_0 == exitcond565_i_fu_852_p2) & ~ap_sig_bdd_199)) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else if ((~ap_sig_bdd_199 & ~(ap_const_lv1_0 == exitcond565_i_fu_852_p2))) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        end
        ap_ST_st14_fsm_13 : 
        begin
            if (~(ap_const_lv1_0 == exitcond564_i_fu_875_p2)) begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end
        end
        ap_ST_st15_fsm_14 : 
        begin
            if (((ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233)) begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end else if ((~(ap_const_lv1_0 == exitcond_i_fu_918_p2) & ~ap_sig_bdd_233)) begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end else begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end
        end
        ap_ST_st16_fsm_15 : 
        begin
            if (~((ap_const_lv1_0 == tmp_62_reg_1331) & (ap_const_logic_0 == grp_sw_pe_array_sw_extend_fu_657_ap_done))) begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st18_fsm_17 : 
        begin
            if (~(pe_matchs_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_17;
            end
        end
        ap_ST_st19_fsm_18 : 
        begin
            if (~(pe_matchs_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end else begin
                ap_NS_fsm = ap_ST_st19_fsm_18;
            end
        end
        ap_ST_st20_fsm_19 : 
        begin
            if (~(pe_matchs_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st20_fsm_19;
            end
        end
        ap_ST_st21_fsm_20 : 
        begin
            if (~(pe_matchs_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_102 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_102 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_114 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_114 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_126 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_126 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_137 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_137 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end

/// ap_sig_bdd_149 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_149 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end

/// ap_sig_bdd_158 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_158 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end

/// ap_sig_bdd_167 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_167 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_176 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_176 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_194 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_194 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end

/// ap_sig_bdd_199 assign process. ///
always @ (pe_seeds_V_empty_n or exitcond565_i_fu_852_p2)
begin
    ap_sig_bdd_199 = ((pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond565_i_fu_852_p2));
end

/// ap_sig_bdd_213 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_213 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end

/// ap_sig_bdd_227 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_227 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_233 assign process. ///
always @ (pe_matchs_V_full_n or exitcond_i_fu_918_p2)
begin
    ap_sig_bdd_233 = ((pe_matchs_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == exitcond_i_fu_918_p2));
end

/// ap_sig_bdd_261 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_261 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end

/// ap_sig_bdd_330 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_330 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end

/// ap_sig_bdd_394 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_394 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end

/// ap_sig_bdd_40 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_40 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_485 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_485 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_504 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_504 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end

/// ap_sig_bdd_514 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_514 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end

/// ap_sig_bdd_523 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_523 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_14]);
end

/// ap_sig_bdd_66 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_66 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_85 assign process. ///
always @ (pe_seeds_V_empty_n or pe_seeds_ctrl_V_V_empty_n or pe_matchs_V_full_n or tmp_nbreadreq_fu_132_p3 or tmp_s_fu_726_p2)
begin
    ap_sig_bdd_85 = (((pe_seeds_ctrl_V_V_empty_n == ap_const_logic_0) & ~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0)) | (~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & (pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp_s_fu_726_p2)) | (~(tmp_nbreadreq_fu_132_p3 == ap_const_lv1_0) & (pe_matchs_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_s_fu_726_p2)));
end

/// ap_sig_bdd_868 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_868 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign aw_0_fu_782_p1 = $signed(w_in_reg_1194);
assign aw_1_2_fu_997_p3 = ((tmp_99_reg_1317[0:0]===1'b1)? grp_sw_pe_array_sw_extend_fu_657_ap_return_1: width_1_reg_212);
assign exitcond564_i_fu_875_p2 = (p_0196_0_i_reg_182 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond565_i_fu_852_p2 = (p_0209_0_i_reg_171 == p_0338_0_i_reg_1273? 1'b1: 1'b0);
assign exitcond_i_fu_918_p2 = (p_0121_0_i_reg_292 == ap_const_lv2_2? 1'b1: 1'b0);
assign grp_fu_708_p3 = ((grp_fu_708_p0[0:0]===1'b1)? tlen_1_V_reg_1219: tlen_0_V_reg_1206);
assign grp_fu_714_p2 = (p_0121_0_i_reg_292 == ap_const_lv2_0? 1'b1: 1'b0);
assign grp_fu_720_p2 = (trueScore_0_i_reg_384 - sc0_reg_282);
assign grp_sw_pe_array_sw_extend_fu_657_ap_start = grp_sw_pe_array_sw_extend_fu_657_ap_start_ap_start_reg;
assign grp_sw_pe_array_sw_extend_fu_657_e_del = e_del_reg_1173;
assign grp_sw_pe_array_sw_extend_fu_657_e_ins = e_ins_reg_1183;
assign grp_sw_pe_array_sw_extend_fu_657_gscore_ret_read = gscore_reg_234;
assign grp_sw_pe_array_sw_extend_fu_657_gtle_ret_read = gtle_reg_246;
assign grp_sw_pe_array_sw_extend_fu_657_h0 = tmp_63_reg_1340;
assign grp_sw_pe_array_sw_extend_fu_657_max_del = max_del_load_phi_reg_1350;
assign grp_sw_pe_array_sw_extend_fu_657_max_ins = tmp_101_reg_1345;
assign grp_sw_pe_array_sw_extend_fu_657_maxoff_ret_read = maxoff_reg_222;
assign grp_sw_pe_array_sw_extend_fu_657_o_del = o_del_reg_1168;
assign grp_sw_pe_array_sw_extend_fu_657_o_ins = o_ins_reg_1178;
assign grp_sw_pe_array_sw_extend_fu_657_qle_ret_read = qle_reg_270;
assign grp_sw_pe_array_sw_extend_fu_657_qlen = op2_assign_reg_1325;
assign grp_sw_pe_array_sw_extend_fu_657_qs_V_q0 = query_mem_V_q0;
assign grp_sw_pe_array_sw_extend_fu_657_qs_baddr_V = p_0_reg_304;
assign grp_sw_pe_array_sw_extend_fu_657_regScore_read = sc0_reg_282;
assign grp_sw_pe_array_sw_extend_fu_657_tle_ret_read = tle_reg_258;
assign grp_sw_pe_array_sw_extend_fu_657_tlen_V = p_08_phi_reg_1335;
assign grp_sw_pe_array_sw_extend_fu_657_ts_baddr_V = p_s_reg_316;
assign grp_sw_pe_array_sw_extend_fu_657_w_in = w_in_reg_1194;
assign h0_fu_778_p1 = pe_seeds_V_dout[7:0];
assign i_V_fu_924_p2 = (p_0121_0_i_reg_292 + ap_const_lv2_1);
assign k_V_fu_857_p2 = (p_0209_0_i_reg_171 + ap_const_lv9_1);
assign l_V_fu_881_p2 = (p_0196_0_i_reg_182 + ap_const_lv4_1);
assign max_ins_load_phi_v_fu_960_p3 = ((tmp_99_fu_930_p1[0:0]===1'b1)? tmp_111_reg_1246: tmp_110_reg_1241);
assign o_del_fu_732_p1 = pe_seeds_V_dout[7:0];
assign op2_assign_fu_935_p3 = ((tmp_99_fu_930_p1[0:0]===1'b1)? qlen_1_reg_1212: qlen_0_reg_1200);
assign p_0338_0_i_fu_844_p3 = ((tmp_58_fu_818_p2[0:0]===1'b1)? r_V_8_cast_fu_834_p1: qrLen_div8_V_2_fu_838_p2);
assign qBeg_0_i_phi_fu_330_p4 = qBeg_0_i_reg_326;
assign qBeg_fu_1091_p2 = (qBeg_ori_reg_1231 - grp_sw_pe_array_sw_extend_fu_657_ap_return_2);
assign qEnd_0_i_phi_fu_353_p4 = qEnd_0_i_reg_350;
assign qEnd_fu_785_p1 = qlen_1_reg_1212;
assign qlen_0_fu_756_p1 = pe_seeds_V_dout[7:0];
assign qlen_1_fu_760_p1 = pe_seeds_V_dout[7:0];
assign qrLen_div8_V_2_fu_838_p2 = (ap_const_lv9_1 + r_V_8_cast_fu_834_p1);
assign qrLen_div8_V_fu_809_p2 = (tlen_0_V_reg_1206 + tmp1_fu_804_p2);
assign qs_baddr_V_fu_1105_p2 = (tmp_158_cast_fu_1102_p1 + p_0_reg_304);
assign query_mem_V_d0 = {{p_0201_0_i_reg_193[ap_const_lv32_1F : ap_const_lv32_1C]}};
assign rBeg_0_i_phi_fu_342_p4 = rBeg_0_i_reg_338;
assign rBeg_1_fu_1096_p2 = (ap_const_lv16_0 - grp_sw_pe_array_sw_extend_fu_657_ap_return_3);
assign rBeg_fu_1079_p2 = (ap_const_lv16_0 - grp_sw_pe_array_sw_extend_fu_657_ap_return_4);
assign rEnd_0_i_phi_fu_364_p4 = rEnd_0_i_reg_360;
assign r_V_1_fu_891_p2 = (rhs_V_cast_fu_887_p1 + r_V_reg_1291);
assign r_V_8_cast_fu_834_p1 = tmp_23_fu_824_p4;
assign r_V_fu_867_p3 = {{tmp_97_fu_863_p1}, {ap_const_lv3_0}};
assign regScore_fu_764_p1 = pe_seeds_V_dout[15:0];
assign rhs_V_cast_fu_887_p1 = p_0196_0_i_reg_182;
assign tmp1_fu_804_p2 = (ts_baddr_V_2_cast_fu_800_p1 + tlen_1_V_reg_1219);
assign tmp_100_fu_948_p1 = sc0_reg_282[7:0];
assign tmp_101_fu_966_p1 = max_ins_load_phi_v_fu_960_p3[15:0];
assign tmp_103_fu_1047_p1 = tmp_105_reg_1188[7:0];
assign tmp_131_cast_fu_788_p1 = qlen_0_reg_1200;
assign tmp_132_cast_fu_791_p1 = qlen_1_reg_1212;
assign tmp_146_cast_fu_1030_p1 = grp_sw_pe_array_sw_extend_fu_657_ap_return_5;
assign tmp_147_cast_fu_1034_p1 = $signed(grp_sw_pe_array_sw_extend_fu_657_ap_return_0);
assign tmp_151_cast_fu_1057_p1 = $signed(tmp_37_fu_1050_p3);
assign tmp_158_cast_fu_1102_p1 = op2_assign_reg_1325;
assign tmp_23_fu_824_p4 = {{qrLen_div8_V_fu_809_p2[ap_const_lv32_A : ap_const_lv32_3]}};
assign tmp_25_fu_1117_p3 = {{qEnd_0_i_reg_350}, {qBeg_0_i_reg_326}};
assign tmp_27_fu_1140_p3 = {{rEnd_0_i_reg_360}, {rBeg_0_i_reg_338}};
assign tmp_29_fu_1149_p3 = {{trueScore_0_i_reg_384}, {score_0_i_reg_372}};
assign tmp_31_fu_1158_p1 = width_2_reg_1475;
assign tmp_35_fu_1038_p4 = {{tmp_105_reg_1188[ap_const_lv32_F : ap_const_lv32_8]}};
assign tmp_37_fu_1050_p3 = ((tmp_99_reg_1317[0:0]===1'b1)? tmp_35_fu_1038_p4: tmp_103_fu_1047_p1);
assign tmp_58_fu_818_p2 = (tmp_95_fu_814_p1 == ap_const_lv3_0? 1'b1: 1'b0);
assign tmp_60_fu_1126_p2 = ($signed(width_reg_202) > $signed(width_1_reg_212)? 1'b1: 1'b0);
assign tmp_62_fu_942_p2 = (op2_assign_fu_935_p3 == ap_const_lv8_0? 1'b1: 1'b0);
assign tmp_63_fu_952_p3 = ((tmp_99_fu_930_p1[0:0]===1'b1)? tmp_100_fu_948_p1: h0_reg_1236);
assign tmp_64_fu_1024_p2 = ($signed(grp_sw_pe_array_sw_extend_fu_657_ap_return_5) < $signed(16'b1)? 1'b1: 1'b0);
assign tmp_65_fu_896_p1 = r_V_1_fu_891_p2;
assign tmp_67_fu_1061_p2 = ($signed(tmp_147_cast_fu_1034_p1) - $signed(tmp_151_cast_fu_1057_p1));
assign tmp_68_fu_1067_p2 = ($signed(tmp_146_cast_fu_1030_p1) > $signed(tmp_67_fu_1061_p2)? 1'b1: 1'b0);
assign tmp_95_fu_814_p1 = qrLen_div8_V_fu_809_p2[2:0];
assign tmp_97_fu_863_p1 = p_0209_0_i_reg_171[7:0];
assign tmp_99_fu_930_p1 = p_0121_0_i_reg_292[0:0];
assign tmp_nbreadreq_fu_132_p3 = pe_seeds_ctrl_V_V_empty_n;
assign tmp_qr_data_1_fu_912_p2 = p_0201_0_i_reg_193 << ap_const_lv32_4;
assign tmp_s_fu_726_p2 = (pe_seeds_ctrl_V_V_dout == ap_const_lv2_3? 1'b1: 1'b0);
assign trueScore_2_fu_1073_p2 = (grp_fu_720_p2 + grp_sw_pe_array_sw_extend_fu_657_ap_return_5);
assign trueScore_4_fu_1085_p2 = (grp_fu_720_p2 + grp_sw_pe_array_sw_extend_fu_657_ap_return_0);
assign ts_baddr_V_2_cast_fu_800_p1 = ts_baddr_V_2_fu_794_p2;
assign ts_baddr_V_2_fu_794_p2 = (tmp_132_cast_fu_791_p1 + tmp_131_cast_fu_788_p1);
assign ts_baddr_V_fu_1111_p2 = (grp_fu_708_p3 + p_s_reg_316);
assign width_2_fu_1132_p3 = ((tmp_60_fu_1126_p2[0:0]===1'b1)? width_reg_202: width_1_reg_212);
assign width_3_fu_990_p3 = ((tmp_99_reg_1317[0:0]===1'b1)? width_reg_202: grp_sw_pe_array_sw_extend_fu_657_ap_return_1);
always @ (posedge ap_clk)
begin
    qEnd_reg_1262[15:8] <= 8'b00000000;
    ts_baddr_V_2_cast_reg_1268[10:9] <= 2'b00;
    r_V_reg_1291[2:0] <= 3'b000;
end



endmodule //sw_pe_array_proc_element

