// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sw_pe_array_proc_element (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        pe_seeds_V_dout,
        pe_seeds_V_empty_n,
        pe_seeds_V_read,
        pe_seeds_ctrl_V_V_dout,
        pe_seeds_ctrl_V_V_empty_n,
        pe_seeds_ctrl_V_V_read,
        pe_matchs_V_din,
        pe_matchs_V_full_n,
        pe_matchs_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_st5_fsm_4 = 7'b10000;
parameter    ap_ST_st6_fsm_5 = 7'b100000;
parameter    ap_ST_st7_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv16_0 = 16'b0000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv16_1 = 16'b1;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] pe_seeds_V_dout;
input   pe_seeds_V_empty_n;
output   pe_seeds_V_read;
input  [1:0] pe_seeds_ctrl_V_V_dout;
input   pe_seeds_ctrl_V_V_empty_n;
output   pe_seeds_ctrl_V_V_read;
output  [31:0] pe_matchs_V_din;
input   pe_matchs_V_full_n;
output   pe_matchs_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg pe_seeds_V_read;
reg pe_seeds_ctrl_V_V_read;
reg[31:0] pe_matchs_V_din;
reg pe_matchs_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [31:0] tmp_68_reg_202;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_52;
wire   [0:0] tmp14_nbreadreq_fu_72_p3;
wire   [0:0] tmp_s_fu_153_p2;
reg    ap_sig_bdd_71;
wire   [15:0] j_4_fu_168_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_82;
wire   [0:0] tmp_57_fu_163_p2;
reg    ap_sig_bdd_88;
wire   [2:0] i_fu_185_p2;
reg   [2:0] i_reg_218;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_98;
wire   [0:0] exitcond_i_fu_179_p2;
reg   [7:0] oneSeedBuf_address0;
reg    oneSeedBuf_ce0;
reg    oneSeedBuf_we0;
wire   [31:0] oneSeedBuf_d0;
wire   [31:0] oneSeedBuf_q0;
reg   [2:0] matchsBuf_address0;
reg    matchsBuf_ce0;
reg    matchsBuf_we0;
wire   [31:0] matchsBuf_d0;
wire   [31:0] matchsBuf_q0;
wire    grp_sw_pe_array_leftright_ext_fu_147_ap_start;
wire    grp_sw_pe_array_leftright_ext_fu_147_ap_done;
wire    grp_sw_pe_array_leftright_ext_fu_147_ap_idle;
wire    grp_sw_pe_array_leftright_ext_fu_147_ap_ready;
wire   [7:0] grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_address0;
wire    grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_ce0;
wire   [31:0] grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_q0;
wire   [2:0] grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_address0;
wire    grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_ce0;
wire    grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_we0;
wire   [31:0] grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_d0;
reg   [15:0] j_reg_124;
reg   [2:0] i_0_i_reg_135;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_148;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_158;
reg    grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg = 1'b0;
wire  signed [63:0] tmp_58_fu_174_p1;
wire   [63:0] tmp_59_fu_191_p1;
wire  signed [31:0] tmp_56_fu_159_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_212;


sw_pe_array_task_parse_oneTaskBuf #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
oneSeedBuf_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( oneSeedBuf_address0 ),
    .ce0( oneSeedBuf_ce0 ),
    .we0( oneSeedBuf_we0 ),
    .d0( oneSeedBuf_d0 ),
    .q0( oneSeedBuf_q0 )
);

sw_pe_array_proc_element_matchsBuf #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
matchsBuf_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( matchsBuf_address0 ),
    .ce0( matchsBuf_ce0 ),
    .we0( matchsBuf_we0 ),
    .d0( matchsBuf_d0 ),
    .q0( matchsBuf_q0 )
);

sw_pe_array_leftright_ext grp_sw_pe_array_leftright_ext_fu_147(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_sw_pe_array_leftright_ext_fu_147_ap_start ),
    .ap_done( grp_sw_pe_array_leftright_ext_fu_147_ap_done ),
    .ap_idle( grp_sw_pe_array_leftright_ext_fu_147_ap_idle ),
    .ap_ready( grp_sw_pe_array_leftright_ext_fu_147_ap_ready ),
    .oneSeedBuf_address0( grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_address0 ),
    .oneSeedBuf_ce0( grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_ce0 ),
    .oneSeedBuf_q0( grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_q0 ),
    .oneMatchBuf_address0( grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_address0 ),
    .oneMatchBuf_ce0( grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_ce0 ),
    .oneMatchBuf_we0( grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_we0 ),
    .oneMatchBuf_d0( grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_d0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88)) begin
            grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_sw_pe_array_leftright_ext_fu_147_ap_ready)) begin
            grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(pe_matchs_V_full_n == ap_const_logic_0))) begin
        i_0_i_reg_135 <= i_reg_218;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_logic_0 == grp_sw_pe_array_leftright_ext_fu_147_ap_done))) begin
        i_0_i_reg_135 <= ap_const_lv3_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88)) begin
        j_reg_124 <= j_4_fu_168_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
        j_reg_124 <= ap_const_lv16_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        i_reg_218 <= i_fu_185_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
        tmp_68_reg_202 <= pe_seeds_V_dout;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_26)
begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_52)
begin
    if (ap_sig_bdd_52) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_82)
begin
    if (ap_sig_bdd_82) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_148)
begin
    if (ap_sig_bdd_148) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_98)
begin
    if (ap_sig_bdd_98) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_158)
begin
    if (ap_sig_bdd_158) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// matchsBuf_address0 assign process. ///
always @ (ap_sig_cseq_ST_st6_fsm_5 or grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_address0 or ap_sig_cseq_ST_st5_fsm_4 or tmp_59_fu_191_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        matchsBuf_address0 = tmp_59_fu_191_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        matchsBuf_address0 = grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_address0;
    end else begin
        matchsBuf_address0 = 'bx;
    end
end

/// matchsBuf_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st6_fsm_5 or grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_ce0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        matchsBuf_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        matchsBuf_ce0 = grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_ce0;
    end else begin
        matchsBuf_ce0 = ap_const_logic_0;
    end
end

/// matchsBuf_we0 assign process. ///
always @ (grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_we0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        matchsBuf_we0 = grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_we0;
    end else begin
        matchsBuf_we0 = ap_const_logic_0;
    end
end

/// oneSeedBuf_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_address0 or ap_sig_cseq_ST_st5_fsm_4 or tmp_58_fu_174_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        oneSeedBuf_address0 = tmp_58_fu_174_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        oneSeedBuf_address0 = grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_address0;
    end else begin
        oneSeedBuf_address0 = 'bx;
    end
end

/// oneSeedBuf_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_bdd_88 or grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_ce0 or ap_sig_cseq_ST_st5_fsm_4)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~ap_sig_bdd_88)) begin
        oneSeedBuf_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        oneSeedBuf_ce0 = grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_ce0;
    end else begin
        oneSeedBuf_ce0 = ap_const_logic_0;
    end
end

/// oneSeedBuf_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or tmp_57_fu_163_p2 or ap_sig_bdd_88)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88)) begin
        oneSeedBuf_we0 = ap_const_logic_1;
    end else begin
        oneSeedBuf_we0 = ap_const_logic_0;
    end
end

/// pe_matchs_V_din assign process. ///
always @ (pe_matchs_V_full_n or ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71 or matchsBuf_q0 or ap_sig_cseq_ST_st7_fsm_6)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(pe_matchs_V_full_n == ap_const_logic_0))) begin
        pe_matchs_V_din = matchsBuf_q0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
        pe_matchs_V_din = ap_const_lv32_FFFFFFFF;
    end else begin
        pe_matchs_V_din = 'bx;
    end
end

/// pe_matchs_V_write assign process. ///
always @ (pe_matchs_V_full_n or ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71 or ap_sig_cseq_ST_st7_fsm_6)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(pe_matchs_V_full_n == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71))) begin
        pe_matchs_V_write = ap_const_logic_1;
    end else begin
        pe_matchs_V_write = ap_const_logic_0;
    end
end

/// pe_seeds_V_read assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71 or ap_sig_cseq_ST_st4_fsm_3 or tmp_57_fu_163_p2 or ap_sig_bdd_88)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88))) begin
        pe_seeds_V_read = ap_const_logic_1;
    end else begin
        pe_seeds_V_read = ap_const_logic_0;
    end
end

/// pe_seeds_ctrl_V_V_read assign process. ///
always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp14_nbreadreq_fu_72_p3 or ap_sig_bdd_71)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~ap_sig_bdd_71)) begin
        pe_seeds_ctrl_V_V_read = ap_const_logic_1;
    end else begin
        pe_seeds_ctrl_V_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or pe_matchs_V_full_n or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2 or ap_sig_bdd_71 or tmp_57_fu_163_p2 or ap_sig_bdd_88 or exitcond_i_fu_179_p2 or grp_sw_pe_array_leftright_ext_fu_147_ap_done or ap_sig_bdd_212)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_212) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else if ((~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (ap_const_lv1_0 == tmp_s_fu_153_p2) & ~ap_sig_bdd_71)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if (((tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & ~ap_sig_bdd_71)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if ((~(ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if (((ap_const_lv1_0 == tmp_57_fu_163_p2) & ~ap_sig_bdd_88)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_logic_0 == grp_sw_pe_array_leftright_ext_fu_147_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            if ((ap_const_lv1_0 == exitcond_i_fu_179_p2)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st7_fsm_6 : 
        begin
            if (~(pe_matchs_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_148 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_148 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_158 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_158 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_212 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_212 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_26 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_52 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_52 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_71 assign process. ///
always @ (pe_seeds_V_empty_n or pe_seeds_ctrl_V_V_empty_n or pe_matchs_V_full_n or tmp14_nbreadreq_fu_72_p3 or tmp_s_fu_153_p2)
begin
    ap_sig_bdd_71 = (((pe_seeds_ctrl_V_V_empty_n == ap_const_logic_0) & ~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0)) | (~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (pe_seeds_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp_s_fu_153_p2)) | (~(tmp14_nbreadreq_fu_72_p3 == ap_const_lv1_0) & (pe_matchs_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_s_fu_153_p2)));
end

/// ap_sig_bdd_82 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_82 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_88 assign process. ///
always @ (pe_seeds_V_empty_n or tmp_57_fu_163_p2)
begin
    ap_sig_bdd_88 = ((pe_seeds_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_57_fu_163_p2));
end

/// ap_sig_bdd_98 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_98 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end
assign exitcond_i_fu_179_p2 = (i_0_i_reg_135 == ap_const_lv3_5? 1'b1: 1'b0);
assign grp_sw_pe_array_leftright_ext_fu_147_ap_start = grp_sw_pe_array_leftright_ext_fu_147_ap_start_ap_start_reg;
assign grp_sw_pe_array_leftright_ext_fu_147_oneSeedBuf_q0 = oneSeedBuf_q0;
assign i_fu_185_p2 = (i_0_i_reg_135 + ap_const_lv3_1);
assign j_4_fu_168_p2 = (j_reg_124 + ap_const_lv16_1);
assign matchsBuf_d0 = grp_sw_pe_array_leftright_ext_fu_147_oneMatchBuf_d0;
assign oneSeedBuf_d0 = pe_seeds_V_dout;
assign tmp14_nbreadreq_fu_72_p3 = pe_seeds_ctrl_V_V_empty_n;
assign tmp_56_fu_159_p1 = $signed(j_reg_124);
assign tmp_57_fu_163_p2 = ($signed(tmp_56_fu_159_p1) < $signed(tmp_68_reg_202)? 1'b1: 1'b0);
assign tmp_58_fu_174_p1 = $signed(j_reg_124);
assign tmp_59_fu_191_p1 = i_0_i_reg_135;
assign tmp_s_fu_153_p2 = (pe_seeds_ctrl_V_V_dout == ap_const_lv2_3? 1'b1: 1'b0);


endmodule //sw_pe_array_proc_element

